routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('recipes', 'RecipeController');
    Route::get('updateRecipeIngredient', 'RecipeController@updateRecipeIngredient')
        ->name('recipes.updateRecipeIngredient');

    Route::resource('ingredients', 'IngredientController');
});

app/Models/Ingredient.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Ingredient
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Ingredient newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Ingredient newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Ingredient query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Ingredient whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Ingredient whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Ingredient whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Ingredient whereUpdatedAt($value)
 */
class Ingredient extends Model
{
    protected $fillable = [
        'name'
    ];
}

app/Http/Controllers/Admin/IngredientController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\IngredientRequest;
use App\Models\Ingredient;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;

class IngredientController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $ingredients = Ingredient::paginate(15);
        return view('admin.ingredient.list', [
            'ingredients' => $ingredients
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return view('admin.ingredient.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param IngredientRequest $request
     * @return Response
     */
    public function store(IngredientRequest $request)
    {
        Ingredient::create($request->all());

        if ($request->ajax()) {
            $ingredients = Ingredient::get(['id', 'name'])->toArray();
            return response()->json(['status' => 1, 'ingredients' => $ingredients]);
        }

        return redirect()->route('ingredients.index');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Ingredient $ingredient
     * @return Response
     */
    public function edit(Ingredient $ingredient)
    {
        return view('admin.ingredient.edit', [
            'ingredient' => $ingredient
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param IngredientRequest $request
     * @param Ingredient $ingredient
     * @return Response
     */
    public function update(IngredientRequest $request, Ingredient $ingredient)
    {
        $ingredient->update($request->all());
        return redirect()->route('ingredients.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Ingredient $ingredient
     * @return Response
     * @throws \Exception
     */
    public function destroy(Ingredient $ingredient)
    {
        $ingredient->delete();
        return redirect()->route('ingredients.index');
    }
}

resources/views/admin/ingredient/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Создание игредиента</h1>
@stop

@section('content')
    <div class="col-md-6">
        <!-- Horizontal Form -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Создание игредиента</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="POST" action="{{route('ingredients.store')}}">
                @csrf
                <div class="box-body">
                    <div class="form-group {{$errors->has('name') ? 'has-error' : ''}}">
                        <label for="input-name" class="col-sm-2 control-label">Название</label>

                        <div class="col-sm-10">
                            <input type="text"
                                   class="form-control"
                                   name="name"
                                   value="{{old('name')}}"
                                   id="input-name"
                                   placeholder="Название ингредиента">
                            @if($errors->has('name'))
                                <span class="help-block">{{$errors->first('name')}}</span>
                            @endif
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a class="btn btn-info" href="{{route('ingredients.index')}}">К списку</a>
                    <button type="submit" class="btn btn-success pull-right">Создать</button>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
        <!-- /.box -->
    </div>
@stop

resources/views/admin/ingredient/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Редактирование ингредиента</h1>
@stop

@section('content')
    <div class="col-md-6">
        <!-- Horizontal Form -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Редактирование ингредиента</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="POST" action="{{route('ingredients.update', $ingredient->id)}}">
                @csrf
                @method('PUT')
                <div class="box-body">
                    <div class="form-group {{$errors->has('name') ? 'has-error' : ''}}">
                        <label for="input-name" class="col-sm-2 control-label">Название</label>

                        <div class="col-sm-10">
                            <input type="text"
                                   class="form-control"
                                   name="name"
                                   value="{{$ingredient->name}}"
                                   id="input-name"
                                   placeholder="Название ингредиента">
                            @if($errors->has('name'))
                                <span class="help-block">{{$errors->first('name')}}</span>
                            @endif
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a class="btn btn-info" href="{{route('ingredients.index')}}">К списку</a>
                    <button type="submit" class="btn btn-success pull-right">Обновить</button>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
        <!-- /.box -->
    </div>
@stop

resources/views/admin/ingredient/list.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Ингредиенты</h1>
@stop

@section('content')
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Ингредиенты</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                    <div class="row">
                        <div class="col-sm-6"></div>
                        <div class="col-sm-6"><a href="{{route('ingredients.create')}}" class="pull-right"><button class="btn btn-success">Создать</button></a></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="example2" class="table table-bordered table-hover dataTable" role="grid"
                                   aria-describedby="example2_info">
                                <thead>
                                <tr role="row">
                                    <th>Название</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($ingredients as $ingredient)
                                <tr role="row" class="odd">
                                    <td>{{$ingredient->name}}</td>
                                    <td>
                                        <a href="{{route('ingredients.edit', $ingredient->id)}}"><button class="btn btn-info"><i class="fa fa-edit"></i></button></a>
                                        <form action="{{route('ingredients.destroy', $ingredient->id)}}" method="post" class="inline">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr role="row">
                                    <th>Название</th>
                                    <th>Действия</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
{{--                            <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1--}}
{{--                                to 10 of 57 entries--}}
{{--                            </div>--}}
                        </div>
                        <div class="col-sm-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                {{$ingredients->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
@stop