routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::resource('recipes', 'RecipeController');
    Route::get('updateRecipeIngredient', 'RecipeController@updateRecipeIngredient')
        ->name('recipes.updateRecipeIngredient');

    Route::resource('ingredients', 'IngredientController');
});

app/Models/Recipe.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Models\Recipe
 *
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\RecipeIngredient[] $ingredients
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Recipe newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Recipe newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Recipe query()
 * @mixin \Eloquent
 * @property int $id
 * @property string $name
 * @property string|null $description
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Recipe whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Recipe whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Recipe whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Recipe whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Recipe whereUpdatedAt($value)
 */
class Recipe extends Model
{
    protected $fillable = [
        'name',
        'description',
    ];

    public function ingredients()
    {
        return $this->hasMany(RecipeIngredient::class);
    }
}

app/Http/Controllers/Admin/RecipeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\RecipeRequest;
use App\Models\Ingredient;
use App\Models\Recipe;
use App\Http\Controllers\Controller;
use App\Models\RecipeIngredient;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class RecipeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $recipes = Recipe::paginate();
        return view('admin.recipe.list', [
            'recipes' => $recipes
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $ingredients = Ingredient::all();
        return view('admin.recipe.create', [
            'ingredients' => $ingredients
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param RecipeRequest $request
     * @return Response
     */
    public function store(RecipeRequest $request)
    {
        $recipe = Recipe::create($request->all());
        if ($request->has('ingredients')) {
            foreach ($request->input('ingredients') as $item) {
                $recipe->ingredients()->create($item);
            }
        }

        return redirect()->route('recipes.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Recipe $recipe
     * @return Response
     */
    public function show(Recipe $recipe)
    {
        $recipe->load('ingredients.ingredient');
        return view('admin.recipe.show', [
            'recipe' => $recipe
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Recipe $recipe
     * @return Response
     */
    public function edit(Recipe $recipe)
    {
        $recipe->load('ingredients.ingredient');
        $ingredients = Ingredient::all();
        return view('admin.recipe.edit', [
            'recipe' => $recipe,
            'ingredients' => $ingredients
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param RecipeRequest $request
     * @param Recipe $recipe
     * @return Response
     */
    public function update(RecipeRequest $request, Recipe $recipe)
    {
        $recipe->update($request->all());
        $recipe->ingredients()->delete();
        if ($request->has('ingredients')) {
            foreach ($request->input('ingredients') as $item) {
                $recipe->ingredients()->create($item);
            }
        }
        return redirect()->route('recipes.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Recipe $recipe
     * @return Response
     * @throws \Exception
     */
    public function destroy(Recipe $recipe)
    {
        $recipe->delete();
        return redirect()->route('recipes.index');
    }

    public function updateRecipeIngredient(Request $request)
    {
        $this->validate($request, [
            'ingredient_id' => 'required',
            'recipe_id' => 'required'
        ]);

        $recipeIngredient = RecipeIngredient::where('ingredient_id', '=', $request->input('ingredient_id'))
            ->where('recipe_id', '=', $request->input('recipe_id'))
            ->first();

        if (isset($recipeIngredient)) {
            $recipeIngredient->quantity = $request->input('quantity');
            $recipeIngredient->save();
            return response()->json(['status' => 1, 'text' => 'Количество обновлено']);
        }
    }
}

resources/views/admin/recipe/create.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Создание рецепта</h1>
@stop

@section('content')
    <div class="col-md-6">
        <!-- Horizontal Form -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Создание рецепта</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="POST" action="{{route('recipes.store')}}">
                @csrf
                <div class="box-body">
                    <div class="form-group {{$errors->has('name') ? 'has-error' : ''}}">
                        <label for="input-name" class="col-sm-2 control-label">Название</label>

                        <div class="col-sm-10">
                            <input type="text"
                                   class="form-control"
                                   name="name"
                                   value="{{old('name')}}"
                                   id="input-name"
                                   placeholder="Название ингредиента">
                            @if($errors->has('name'))
                                <span class="help-block">{{$errors->first('name')}}</span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group {{$errors->has('description') ? 'has-error' : ''}}">
                        <label for="input-description" class="col-sm-2 control-label">Описание</label>

                        <div class="col-sm-10">
                            <textarea class="form-control"
                                      name="description"
                                      id="input-description"
                                      placeholder="Название рецепта">{{old('description')}}</textarea>
                            @if($errors->has('name'))
                                <span class="help-block">{{$errors->first('description')}}</span>
                            @endif
                        </div>
                    </div>

                    <div>
                        <table class="table table-bordered text-center">
                            <thead>
                            <tr>
                                <td>Название</td>
                                <td>Количество</td>
                                <td>Действие</td>
                            </tr>
                            </thead>
                            <tbody id="ingredients">
                            </tbody>
                        </table>
                    </div>
                    <div>
                        <div class="col-sm-4">
                            <button class="btn btn-success" id="add-ingredient">Добавить</button>
                        </div>
                        <div class="col-sm-4"><span>Нет в списке?</span></div>
                        <div class="col-sm-4"><a class="mfp-popup" href="#create-ingredient">Создать новый
                                ингредиент</a></div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a class="btn btn-info" href="{{route('recipes.index')}}">К списку</a>
                    <button type="submit" class="btn btn-success pull-right">Создать</button>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
        <!-- /.box -->
    </div>

    <div class="hidden">
        <form id="create-ingredient" class="popup">
            @csrf
            <div class="form-group">
                <label for="ingredient-name" class="col-sm-2 control-label">Название</label>
                <div class="col-sm-10">
                    <input id="ingredient-name"
                           class="form-control"
                           type="text"
                           name="name"
                           placeholder="Название ингредиента">
                </div>
            </div>
            <button type="submit" class="btn btn-success">Создать</button>
        </form>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/magnific-popup.css')}}">
    <style>
        .popup {
            padding: 60px 30px 30px;
            background: #fff;
            position: relative;
            max-width: 500px;
            margin: auto;
        }
    </style>
@stop

@section('js')
    <script src="{{asset('js/jquery.magnific-popup.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('.mfp-popup').magnificPopup({
                type: 'inline',
                preloader: false,
                focus: '#name',

                // When elemened is focused, some mobile browsers in some cases zoom in
                // It looks not nice, so we disable it:
                callbacks: {
                    beforeOpen: function () {
                        if ($(window).width() < 700) {
                            this.st.focus = false;
                        } else {
                            this.st.focus = '#name';
                        }
                    }
                }
            });
        });

        var ingredientsTable = {
            ingredients: @json($ingredients),
            recipeIngredients: [],
            updateRecipeIngredients: function () {
                this.recipeIngredients = [];
                var rows = $('#ingredients tr');
                for (var i = 0; i < rows.length; i++ ) {
                    var row = rows[i];
                    var ingredientId = $(row).find('select').val();
                    var quantity = $(row).find('input').val();
                    this.recipeIngredients.push({
                        ingredientId: ingredientId,
                        quantity: quantity
                    });
                }
            },
            updateRows: function () {
                $('#ingredients').html('');
                for (var i = 0; i < this.recipeIngredients.length; i++) {
                    var recipeIngredient = this.recipeIngredients[i];
                    var template = $(this.rowTemplate).clone();
                    template.find('input').attr('name', 'ingredients[' + i +'][quantity]').val(recipeIngredient.quantity);
                    template.find('select').attr('name', 'ingredients[' + i +'][ingredient_id]');
                    var options = '';
                    for (var b = 0; b < this.ingredients.length; b++) {
                        var ingredient = this.ingredients[b];
                        var isSelected = parseInt(ingredient.id) == parseInt(recipeIngredient.ingredientId);
                        options += '<option value="' + ingredient.id + '" '
                            + (isSelected ? 'selected' : '') + '>'
                            + ingredient.name + '</option>'
                    }
                    template.find('select').html(options);
                    $('#ingredients').append(template);
                }

            },
            addRow: function () {
                $('#ingredients').append(this.rowTemplate);
            },
            rowTemplate: '<tr>\n' +
                '             <td>\n' +
                '                 <select name="">\n' +
                '                 </select>\n' +
                '             </td>\n' +
                '             <td>\n' +
                '                 <input type="text" name="">\n' +
                '             </td>\n' +
                '             <td>\n' +
                '                 <button class="btn btn-danger delete-ingredient">Удалить</button>\n' +
                '             </td>\n' +
                '         </tr>'
        };

        ingredientsTable.updateRecipeIngredients();
        ingredientsTable.updateRows();

        $('#add-ingredient').on('click', function (e) {
            e.preventDefault();
            ingredientsTable.addRow();
            ingredientsTable.updateRecipeIngredients();
            ingredientsTable.updateRows();
        });

        $(document).on('click', '.delete-ingredient', function (e) {
            e.preventDefault();
            $(this).closest('tr').remove();
            ingredientsTable.updateRecipeIngredients();
            ingredientsTable.updateRows();
        });

        $('#create-ingredient').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                'url': '{{route('ingredients.store')}}',
                'data': $(this).serialize(),
                'type': 'post',
                'success': function (result) {
                    if (result && result['status'] === 1) {
                        ingredientsTable.ingredients = result['ingredients'];
                        ingredientsTable.updateRows();
                        alert('Ингредиент создан');
                    }
                }
            });
        });

    </script>
@stop

resources/views/admin/recipe/edit.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Создание рецепта</h1>
@stop

@section('content')
    <div class="col-md-6">
        <!-- Horizontal Form -->
        <div class="box box-info">
            <div class="box-header with-border">
                <h3 class="box-title">Создание рецепта</h3>
            </div>
            <!-- /.box-header -->
            <!-- form start -->
            <form class="form-horizontal" method="POST" action="{{route('recipes.update', $recipe->id)}}">
                @csrf
                @method('PUT')
                <div class="box-body">
                    <div class="form-group {{$errors->has('name') ? 'has-error' : ''}}">
                        <label for="input-name" class="col-sm-2 control-label">Название</label>

                        <div class="col-sm-10">
                            <input type="text"
                                   class="form-control"
                                   name="name"
                                   value="{{old('name', $recipe->name)}}"
                                   id="input-name"
                                   placeholder="Название ингредиента">
                            @if($errors->has('name'))
                                <span class="help-block">{{$errors->first('name')}}</span>
                            @endif
                        </div>
                    </div>
                    <div class="form-group {{$errors->has('description') ? 'has-error' : ''}}">
                        <label for="input-description" class="col-sm-2 control-label">Описание</label>

                        <div class="col-sm-10">
                            <textarea class="form-control"
                                      name="description"
                                      id="input-description"
                                      placeholder="Название рецепта">{{old('description', $recipe->description)}}</textarea>
                            @if($errors->has('name'))
                                <span class="help-block">{{$errors->first('description')}}</span>
                            @endif
                        </div>
                    </div>

                    <div>
                        <table class="table table-bordered text-center">
                            <thead>
                            <tr>
                                <td>Название</td>
                                <td>Количество</td>
                                <td>Действие</td>
                            </tr>
                            </thead>
                            <tbody id="ingredients">
                            @foreach($recipe->ingredients as $recipeIngredient)
                                <tr>
                                    <td>
                                        <select name="">
                                            @foreach($ingredients as $ingredient)
                                                <option value="{{$ingredient->id}}"
                                                        {{$recipeIngredient->ingredient_id == $ingredient->id ? 'selected' : ''}}
                                                >{{$ingredient->name}}</option>
                                            @endforeach
                                        </select>
                                    </td>
                                    <td>
                                        <input type="text" name="" value="{{$recipeIngredient->quantity}}">
                                    </td>
                                    <td>
                                        <button class="btn btn-danger delete-ingredient">Удалить</button>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div>
                        <div class="col-sm-4">
                            <button class="btn btn-success" id="add-ingredient">Добавить</button>
                        </div>
                        <div class="col-sm-4"><span>Нет в списке?</span></div>
                        <div class="col-sm-4"><a class="mfp-popup" href="#create-ingredient">Создать новый
                                ингредиент</a></div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a class="btn btn-info" href="{{route('recipes.index')}}">К списку</a>
                    <button type="submit" class="btn btn-success pull-right">Создать</button>
                </div>
                <!-- /.box-footer -->
            </form>
        </div>
        <!-- /.box -->
    </div>

    <div class="hidden">
        <form id="create-ingredient" class="popup">
            @csrf
            <div class="form-group">
                <label for="ingredient-name" class="col-sm-2 control-label">Название</label>
                <div class="col-sm-10">
                    <input id="ingredient-name"
                           class="form-control"
                           type="text"
                           name="name"
                           placeholder="Название ингредиента">
                </div>
            </div>
            <button type="submit" class="btn btn-success">Создать</button>
        </form>
    </div>
@stop

@section('css')
    <link rel="stylesheet" href="{{asset('css/magnific-popup.css')}}">
    <style>
        .popup {
            padding: 60px 30px 30px;
            background: #fff;
            position: relative;
            max-width: 500px;
            margin: auto;
        }
    </style>
@stop

@section('js')
    <script src="{{asset('js/jquery.magnific-popup.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('.mfp-popup').magnificPopup({
                type: 'inline',
                preloader: false,
                focus: '#name',

                // When elemened is focused, some mobile browsers in some cases zoom in
                // It looks not nice, so we disable it:
                callbacks: {
                    beforeOpen: function () {
                        if ($(window).width() < 700) {
                            this.st.focus = false;
                        } else {
                            this.st.focus = '#name';
                        }
                    }
                }
            });
        });

        var ingredientsTable = {
            ingredients: @json($ingredients),
            recipeIngredients: [],
            updateRecipeIngredients: function () {
                this.recipeIngredients = [];
                var rows = $('#ingredients tr');
                for (var i = 0; i < rows.length; i++) {
                    var row = rows[i];
                    var ingredientId = $(row).find('select').val();
                    var quantity = $(row).find('input').val();
                    this.recipeIngredients.push({
                        ingredientId: ingredientId,
                        quantity: quantity
                    });
                }
            },
            updateRows: function () {
                $('#ingredients').html('');
                for (var i = 0; i < this.recipeIngredients.length; i++) {
                    var recipeIngredient = this.recipeIngredients[i];
                    var template = $(this.rowTemplate).clone();
                    template.find('input').attr('name', 'ingredients[' + i + '][quantity]').val(recipeIngredient.quantity);
                    template.find('select').attr('name', 'ingredients[' + i + '][ingredient_id]');
                    var options = '';
                    for (var b = 0; b < this.ingredients.length; b++) {
                        var ingredient = this.ingredients[b];
                        var isSelected = parseInt(ingredient.id) == parseInt(recipeIngredient.ingredientId);
                        options += '<option value="' + ingredient.id + '" '
                            + (isSelected ? 'selected' : '') + '>'
                            + ingredient.name + '</option>'
                    }
                    template.find('select').html(options);
                    $('#ingredients').append(template);
                }

            },
            addRow: function () {
                $('#ingredients').append(this.rowTemplate);
            },
            rowTemplate: '<tr>\n' +
                '             <td>\n' +
                '                 <select name="">\n' +
                '                 </select>\n' +
                '             </td>\n' +
                '             <td>\n' +
                '                 <input type="text" name="">\n' +
                '             </td>\n' +
                '             <td>\n' +
                '                 <button class="btn btn-danger delete-ingredient">Удалить</button>\n' +
                '             </td>\n' +
                '         </tr>'
        };

        ingredientsTable.updateRecipeIngredients();
        ingredientsTable.updateRows();

        $('#add-ingredient').on('click', function (e) {
            e.preventDefault();
            ingredientsTable.addRow();
            ingredientsTable.updateRecipeIngredients();
            ingredientsTable.updateRows();
        });

        $(document).on('click', '.delete-ingredient', function (e) {
            e.preventDefault();
            $(this).closest('tr').remove();
            ingredientsTable.updateRecipeIngredients();
            ingredientsTable.updateRows();
        });

        $('#create-ingredient').on('submit', function (e) {
            e.preventDefault();

            $.ajax({
                'url': '{{route('ingredients.store')}}',
                'data': $(this).serialize(),
                'type': 'post',
                'success': function (result) {
                    if (result && result['status'] === 1) {
                        ingredientsTable.ingredients = result['ingredients'];
                        ingredientsTable.updateRows();
                        alert('Ингредиент создан');
                    }
                }
            });
        });

    </script>
@stop

resources/views/admin/recipe/list.blade.php
@extends('adminlte::page')

@section('title', 'Dashboard')

@section('content_header')
    <h1>Рецепты</h1>
@stop

@section('content')
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Рецепты</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body">
                <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                    <div class="row">
                        <div class="col-sm-6"></div>
                        <div class="col-sm-6"><a href="{{route('recipes.create')}}" class="pull-right"><button class="btn btn-success">Создать</button></a></div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <table id="example2" class="table table-bordered table-hover dataTable" role="grid"
                                   aria-describedby="example2_info">
                                <thead>
                                <tr role="row">
                                    <th>Название</th>
                                    <th>Описание</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach($recipes as $recipe)
                                    <tr role="row" class="odd">
                                        <td>{{$recipe->name}}</td>
                                        <td>{{$recipe->description}}</td>
                                        <td>
                                            <a href="{{route('recipes.show', $recipe->id)}}"><button class="btn btn-info"><i class="fa fa-eye"></i></button></a>
                                            <a href="{{route('recipes.edit', $recipe->id)}}"><button class="btn btn-info"><i class="fa fa-edit"></i></button></a>
                                            <form action="{{route('recipes.destroy', $recipe->id)}}" method="post" class="inline">
                                                @csrf
                                                @method('DELETE')
                                                <button type="submit" class="btn btn-danger"><i class="fa fa-trash"></i></button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                                <tfoot>
                                <tr role="row">
                                    <th>Название</th>
                                    <th>Описание</th>
                                    <th>Действия</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-5">
                            {{--                            <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing 1--}}
                            {{--                                to 10 of 57 entries--}}
                            {{--                            </div>--}}
                        </div>
                        <div class="col-sm-7">
                            <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                {{$recipes->links()}}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
@stop